# Generated by Django 3.0.4 on 2020-04-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('email_id', models.EmailField(max_length=254)),
                ('regno', models.TextField()),
                ('timetable', models.ImageField(upload_to='timetables/')),
            ],
        ),
    ]
