# Generated by Django 3.0.4 on 2020-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kinder', '0002_kinder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='regno',
            field=models.TextField(max_length=9),
        ),
    ]
