# Generated by Django 3.0.5 on 2020-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kinder', '0003_auto_20200412_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinder',
            name='regno',
            field=models.CharField(max_length=9),
        ),
    ]
